---
title: "ESM 204 Homework 3"
author: "Elmera Azadpour, Genevieve Chiong, and Kristin Gill"
date: "5/3/2021"
output: 
   html_document:
     code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(janitor)
library(here)
library(kableExtra)
library(formattable)
library(priceR)
```

```{r}
# read in the data
gas_tax_data <- read_csv(here("data", "HW3_data.csv")) %>% 
  clean_names()
```

Result: P = 12 - 6.6x10^-5Q
```{r}
# linear regression low income
ggplot(data = gas_tax_data, aes(x = q_low_gallons,
                                y = price_dollars)) +
  geom_line() +
  labs(x = "\nQuantity (gallons of gas)",
       y = "Price ($/gallon)\n") +
  theme_minimal() +
    geom_smooth(method = "lm",
              color = "black",
              size = 0.5,
              fill = "gray10",
              alpha = 0.5) +
  ggpubr::stat_regline_equation(label.x = 12000, label.y = 5) +
  ggpubr::stat_cor(label.x = 60000, label.y = 10)
```

Result: P = 16 - 2.7x10^-5Q
```{r}
# linear regression high income
ggplot(data = gas_tax_data, aes(x = q_high_gallons,
                                y = price_dollars)) +
  geom_line() +
  labs(x = "\nQuantity (gallons of gas)",
       y = "Price ($/gallon)\n") +
  theme_minimal() +
  geom_smooth(method = "lm",
              color = "black",
              size = 0.5,
              fill = "gray10",
              alpha = 0.5) +
  ggpubr::stat_regline_equation(label.x = 190000, label.y = 5) +
  ggpubr::stat_cor(label.x = 300000, label.y = 10)
```

```{r}
# creating data frames for the linear regression
low_df <- data.frame(price = seq.int(from = 0, to = 16)) %>% 
  mutate(quantity = (12 - price)/(6.6e-5))

high_df <- data.frame(price = seq.int(from = 0, to = 16)) %>% 
  mutate(quantity = (16 - price)/(2.7e-5))
```

```{r}
# graphing the two demand curves together
ggplot() +
  geom_line(data = low_df, aes(x = quantity,
                               y = price,
                               color = "red")) +
  geom_line(data = high_df, aes(x = quantity,
                                y = price,
                                color = "blue")) +
  labs(x = "\nQuantity (gallons of gas)",
       y = "Price ($/gallon)\n",
       color = "Income Group",
       title = "Marginal Benefit of Gas Use by Income Group") +
  theme_minimal() +
  scale_x_continuous(limit = c(0,600000)) +
  scale_color_manual(labels = c("High Income", "Low Income"), values = c("blue", "red"))
```

```{r}
aggregate_df <- data.frame(price = seq.int(from = 0, to = 20)) %>% 
  mutate(quantity = (14.84 - price)/(1.92e-5))

ggplot() +
  geom_line(data = low_df, aes(x = quantity,
                               y = price,
                               color = "red")) +
  geom_line(data = high_df, aes(x = quantity,
                                y = price,
                                color = "blue")) +
  geom_line(data = aggregate_df, aes(x = quantity,
                                     y = price)) +
  labs(x = "\nQuantity (gallons of gas)",
       y = "Price ($/gallon)\n",
       color = "Income Group",
       title = "Marginal Benefit of Gas Use by Income Group") +
  theme_minimal() +
  scale_x_continuous(limit = c(0,600000)) +
  scale_y_continuous(limit = c(0,20)) +
  scale_color_manual(labels = c("High Income", "Low Income"), values = c("blue", "red"))
```

```{r}
# creating a function for #5
mec <- function() {
  for(i in 51:150) {
    print(7.9e-5*i)
  }
}
```

```{r}
# actually creating df
numb5_df <- data.frame(scc = seq.int(from = 51, to = 150)) %>% 
  mutate(MEC = 0.00889*scc) %>% 
  mutate(Quantity = (14.84 - MEC)/0.00002406) %>% 
  mutate(Price = (14.84 - ((1.92e-5)*Quantity))) %>% 
  mutate(hcs = .5*(16-Price)*((16-Price)/2.7e-5)) %>% 
  mutate(lcs = .5*(12-Price)*((12-Price)/6.6e-5)) %>% 
  mutate(ps = .5*(Price-MEC)*Quantity) %>% 
  mutate(percent_hcs = hcs/(hcs + lcs)) %>% 
  mutate(percent_lcs = lcs/(hcs + lcs)) %>% 
  mutate(tax_rev = Quantity*MEC) %>% 
  mutate(welfare_hcs = hcs + (percent_hcs*tax_rev)) %>% 
  mutate(welfare_lcs = lcs + (percent_lcs*tax_rev)-tax_rev) %>% 
  rename("High Income Consumer Surplus (HCS)" = "hcs") %>% 
  rename("Low Income Consumer Surplus (LCS)" = "lcs") %>% 
  rename("Percent HCS" = "percent_hcs") %>% 
  rename("Percent LCS" = "percent_lcs") %>% 
  rename("Tax Revenue" = "tax_rev") %>% 
  rename("Quantity(gallons)" = "Quantity")
```

```{r}
# result table
numb5_results <- numb5_df %>% 
  filter(scc %in% c("51", "75", "100", "125", "150")) %>% 
  select(scc, MEC, welfare_hcs, welfare_lcs, ps) %>% 
  rename("Producer Surplus" = "ps") %>% 
  rename("Social Cost of Carbon" = "scc") %>% 
  rename("Welfare HCS" = "welfare_hcs") %>% 
  rename("Welfare LCS" = "welfare_lcs") %>% 
  rename("Marginal External Cost" = "MEC")
  
kbl(numb5_results, caption = "Table 1: Results for different estimates of the social cost of carbon. All values are in dollars.") %>% 
   kable_styling(latex_options = c("striped", "hold_position"),
                full_width = F)
```


